version: '3.1'

services:
  mongo:
    image: mongo
    container_name: "mongo_walldo"
    restart: always
    env_file:
      - ./mongocreds.env
    volumes:
      - ./mongo_data/db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongocreds.env