# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

servers=[
  {
	:hostname => "vm1",
#	:ip => "192.168.56.200",
	:box => "ubuntu/trusty64",
	:ram => 512,
	:cpu => 1
  },
  {
	:hostname => "vm2",
#	:ip => "192.168.56.202",
	:box => "centos/7",
	:ram => 512,
	:cpu => 1
  },
  {
	:hostname => "vm3",
#	:ip => "192.168.56.203",
	:box => "debian/jessie64",
	:ram => 512,
	:cpu => 1
  }
  ]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	servers.each do |machine|
		config.vm.define machine[:hostname] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:hostname]
#			node.vm.network "private_network", ip: machine[:ip]
			node.vm.network "public_network"
  			node.vm.provider "virtualbox" do |vb|
  				vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
  			end
  		end
	end
end
